### ISSUE TITLE
Allow Inline Edit on key press

### ISSUE THREAD

**Issue by AndreasPatsimas** [giorgosart/react-easy-edit#103]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by AndreasPatsimas** [comment]
It would be very useful to enable inline editing on key press. I think that this feature is not supported by your libray.
If I am wrong please guide me.
Thanks fro your time!

**Comment by giorgosart** [comment]
Hey @AndreasPatsimas thank you for logging a ticket with me. Help me understand this, let's assume that you have 5 EasyEdit components in a page and you start editing one, would you then press `tab` to move to the next one? So the next EasyEdit component's state would go from `viewing` to `editing`?

**Comment by AndreasPatsimas** [comment]
Exactly this!

**Comment by giorgosart** [comment]
@AndreasPatsimas I don't see how this could be implemented in the library itself as I will need to know any other occurrences of an `EasyEdit` component, and also there needs to be some sort of order so not sure I can support this. You could always add a wrapper component that would group all the `EasyEdit` components and have that do what you want to do above. Let me know if you have something else in mind.
