### ISSUE TITLE
Decide between using a controlled or uncontrolled input element on Date input

### ISSUE THREAD

**Issue by yeomann** [giorgosart/react-easy-edit#104]
**Describe the bug**
using of the Date input, when you select the date, it give Decide between using a controlled or uncontrolled input element on Date error

**To Reproduce**
https://codesandbox.io/s/react-easy-edit-sandbox-2y97j?file=/src/index.js:94-109
Select date and see console

**Expected behavior**
Nothing to be in Console.

**Screenshots**
![image](https://user-images.githubusercontent.com/5970751/88188202-2d683a00-cc40-11ea-84ad-e6ff957eab6c.png)

**Comment by giorgosart** [comment]
Hey @yeomann thank you for logging this with me, i'll take a look as soon as I can.
