### ISSUE TITLE
Trigger edit mode from other components

### ISSUE THREAD

**Issue by alexferrari88** [giorgosart/react-easy-edit#106]
Would it be possible to get a <EasyEdit> component to go in edit mode by, for instance, clicking on another component (for instance a button)?

To make it clear, I'll tell you what I'm trying to do.
I have a card with different EasyEdit components. I want that when users click a button called "Edit", all the EasyEdit enter the edit mode so users can edit them.

Let me know if it's not clear.
Thank you in advance for your work!

**Comment by giorgosart** [comment]
@alexferrari88 I'll add it to the next release, thank you for raising a ticket!
