### ISSUE TITLE
onClickAwayToggleEdit prop (true/false) as well as a delete button

### ISSUE THREAD

**Issue by midimurphdesigns** [giorgosart/react-easy-edit#107]
I want to make it so when the user clicks away from from the component, it toggles edit mode. So, I would like to see a prop called onClickAwayToggleEdit (true/false) that allows the component to toggle itself on click away.

I would also like to see a delete button to the right of the cancel button.

**Comment by giorgosart** [comment]
@midimurphdesigns would you please provide me with a use case for this enhancement? Just so that I understand, you want this prop to enable the component to store its value whether the user clicks away?

Would this satisfy your use case? 

--> https://giorgosart.gitbook.io/react-easy-edit/examples/onblur <--

### Auto-saving onBlur
You can configure an EasyEdit component to auto-save its value when it loses focus.

```
<EasyEdit
    type="text"
    value="Auto-submit onBlur"
    onSave={App.onTest}
    saveOnBlur
/>
```

**Comment by midimurphdesigns** [comment]
Sorry for the delayed response. My use case is I'm making an EHR (electronic health record) with complex forms and fields. I'm using this library to be able to easily edit individual fields. At the moment, when the user clicks to edit the field and then clicks away nothing happens. I want the field to cancel when they click away. I am also adding a delete button (to delete the field and make it's value null) to the side of the cancel button on my own. I want this to cancel as well when the user clicks away from the field. At the moment my work around with the delete button isn't ideal and has its own caveats. I am also unable to figure out how to use onBlur to close/cancel the editing field. If I have time I'll pull down the repo and try to add this myself. However, free time is hard to come by for me working 7 days a week.

**Comment by giorgosart** [comment]
Hey @midimurphdesigns,

There are a lot of requests as part of this ticket, and some of them are not not very clear. To summarise:

1. You want a new prop called `cancelOnBlur` that would change the state of the component from `editing` to `viewing` and to not store the value the user has inputted.
2. You want a new button `Delete` to be added after the Save and Cancel buttons that would remove the `EasyEdit` component when clicked.
3. You want the component to be able to change from a textInput to a textArea. _Not clear on this requirement, can you please elaborate?_ It would be good if you log another ticket for this.
4. Not clear what you mean with the `isOpen` prop that you are requesting.

Let me check the onBlur one, I will add the delete button in for you and it would be great if you could either get back to me on points 3 and 4 or log separate tickets for them.

Thanks for using `react-easy-edit`, if you like the repo please dont forget to star it!

**Comment by midimurphdesigns** [comment]
1. yes, a cancelOnBlur prop that would change the state of the component from editing to viewing and to not store the value the user has inputted.
2. A delete button that can be included/hidden with a showDeleteButton prop (default is true). then, also an onClickDelete prop that is a callback for when the user clicks the delete button.
3. will make another ticket
4. will make another ticket

**Comment by giorgosart** [comment]
great thanks for confirming @midimurphdesigns

**Comment by giorgosart** [comment]
@midimurphdesigns please check the latest react-easy-edit version [1.11.0](https://github.com/giorgosart/react-easy-edit/releases/tag/1.11.0) where I've added most of the features you've requested. I've also updated the docs with examples to reflect the latest changes in the library.

- [Enable the `Delete` button](https://giorgosart.gitbook.io/react-easy-edit/examples/enable-the-delete-button)
- [Toggle `editMode` for multiple components](https://giorgosart.gitbook.io/react-easy-edit/examples/toggle-edit-mode-for-multiple-components)

Please log individual tickets for any other feature requests. 

Thanks!
