### ISSUE TITLE
Documentation for props incorrectly uses submitOnBlur instead of saveOnBlur 

### ISSUE THREAD

**Issue by VictorPapyshev** [giorgosart/react-easy-edit#108]
The documentation incorrectly lists and uses submitOnBlur as a prop instead of saveOnBlur.

Love your work; thank you!

**Comment by giorgosart** [comment]
Oops, will correct it asap, thank you for letting me know!

**Comment by giorgosart** [comment]
@VictorPapyshev docs updated, will close the ticket now
