### ISSUE TITLE
add textArea capabilities

### ISSUE THREAD

**Issue by midimurphdesigns** [giorgosart/react-easy-edit#111]
For larger fields with large amounts of text, make it able to support a textArea. Include a prop called isTextArea (default is false). If set to true, when the user clicks on the editable field it shows a textArea component instead of a textInput component. It would function the same as the already supported textInput component, but it would give the user a little more space to write a longer answer to save. 

At the moment, the user is not able to see their entire answer in the textInput component making it hard for them to make changes to longer text fields.

**Comment by giorgosart** [comment]
Hey @midimurphdesigns, text area is already supported in `react-easy-edit`, please see below.

`<EasyEdit type={Types.TEXTAREA} onSave={save} onCancel={cancel} />`

**Comment by giorgosart** [comment]
@midimurphdesigns closing this ticket down, let me know if you believe that the library does not support what you want to do, happy to discuss further.
