### ISSUE TITLE
Allow custom editComponent to work with saveOnBlur behavior.

### ISSUE THREAD

**Issue by mrrenaud** [giorgosart/react-easy-edit#116]
**Is your feature request related to a problem? Please describe.**
There is no way to use the **saveOnBlur** behavior while using a custom **editComponent**.

**Describe the solution you'd like**
Passe the onBlur function to the custom component

**Describe alternatives you've considered**
I don't see no alternative. 

**Additional context**
I forked the repo, added a component in the demo app, and I added two unit tests.
I proposed a PR #117

**Comment by giorgosart** [comment]
@mrrenaud I've published the fix you've made in 1.12.0, please let me know if it works for you. Thank you for your contribution to the project!
