### ISSUE TITLE
The component value is not updateded when the state changes 

### ISSUE THREAD

**Issue by joingenor** [giorgosart/react-easy-edit#12]
I am trying to use this component:

<EasyEdit
                type="textarea"
                onSave={(e)=>{this.handleBuildingSave(e,'info');}}
                onValidate={() => true}
                value={selectedBuilding.info}
                saveButtonLabel={getLocalizedStrings(userLang).SAVE}
                cancelButtonLabel={getLocalizedStrings(userLang).CANCEL}
                saveButtonStyle={'button'}
                cancelButtonStyle={'button'}
                attributes={{name: 'buildingInfo',
                  rows:'5',
                  cols:'35',
                  id: 'name-buildingInfo',style:inlineEditStyle}}
              />
<div>{selectedBuilding.info}</div> // this displays correctly

The selectedBuilding.info are a coming from redux store. When my redux store update this value the value in the EasyEdit component is not updated. If I show the redux store value in a div it shows the correct value.

**Comment by giorgosart** [comment]
@joingenor thank you for the bug report, let me take a look at this, will get back to you asap

**Comment by giorgosart** [comment]
Hello @joingenor we will fix this issue in our next minor release, shouldn't take too long to fix this, I was able to replicate your issue

**Comment by giorgosart** [comment]
Fixed as part of 0.3.1

**Comment by joingenor** [comment]
sweet.... That was fast response.... 😀

Sendt fra min iPhone

**Comment by giorgosart** [comment]
No prob. Let me know if you find any other bugs
