### ISSUE TITLE
Ability to edit the properties input/textarea if one doesn't already exists.

### ISSUE THREAD

**Issue by realArcherL** [giorgosart/react-easy-edit#126]
**Is your feature request related to a problem? Please describe.**
Hi, I am trying to add the text area field to my project. I want the length of the text area to take the whole space in the element it is in. I am using Tailwind CSS, so something like "w-full".

![image](https://user-images.githubusercontent.com/42532003/121247988-7eb50280-c8c0-11eb-8113-d44da62a1635.png)

**Describe the solution you'd like**
I am not sure, if there is currently a feature that allows editing as such, I went through the documentation and couldn't find anything about it! 

thanks!!

regards,
@realArcherL

**Comment by giorgosart** [comment]
Hey @realArcherL thank you for logging this ticket with me. 

Will you be able to create a codepen showing the issue you are facing?

The way I would go about fixing this would be to just amend the CSS of the component itself.

**Comment by realArcherL** [comment]
Hi, @giorgosart I was able to do workaround, but it would be very nice if there was a prop which allowed editing the styles!! Thanks!

**Comment by giorgosart** [comment]
Hey @realArcherL, have you had a look at these pages - https://giorgosart.gitbook.io/react-easy-edit/styling. You can also pass css classes in the component via the `attributes` prop as well.

**Comment by realArcherL** [comment]
I went through docs twice, not sure how come I missed it! Thanks! I will be closing this issue now!
