### ISSUE TITLE
Empty string hides the placeholder

### ISSUE THREAD

**Issue by kevko2020** [giorgosart/react-easy-edit#139]
**Describe the bug**
If you enter a value then delete it. The placeholder is gone and there's no way to edit it.

**To Reproduce**
1. In a text/ text area, enter some value save.
2. Edit it and remove all characters then save.
3. The whole component is empty.

**Expected behavior**
The placeholder should show again so it's clickable to edit. 

**Desktop (please complete the following information):**
 - OS: macOS
 - Chrome

**Comment by giorgosart** [comment]
Hi @kevko2020, can you please create a codepen for this issue?

**Comment by kevko2020** [comment]
What's a codepen?

**Comment by darrenplace** [comment]
Hello @giorgosart,

I'm experiencing the same issue and have recreated the issue in [this codesandbox.](https://codesandbox.io/s/summer-violet-3xl98?file=/src/index.js)

With the version used in the documentation (1.7.0) things work as expected. When all text is removed and the changes are submitted, the placeholder text appears.

However, in the latest version (1.15.0) the component seems to disappear once a blank textbook is submitted.

Thanks for creating this awesome module!

**Comment by methodman7556** [comment]
Looks like it works in 1.14.0

**Comment by giorgosart** [comment]
@kevko2020, @darrenplace this will be fixed in the next release in queue.
