### ISSUE TITLE
Requesting an error state

### ISSUE THREAD

**Issue by lauraz33** [giorgosart/react-easy-edit#140]
**Is your feature request related to a problem? Please describe.**
I am having trouble building a nice error handling UX. I am using my own "editComponent" and when the user hits the save button, I am making an api  call in onSave to store the data. But if I have an api error I'm struggling finding a good way to display that.

**Describe the solution you'd like**
I would like if there is an error prop bool that will handle some of that logic. Also possibly the onSave func can return an error or be falsey and the input will remain in edit mode and the user will see the error (similar to how onValidate works). 

**Describe alternatives you've considered**
I tried to call my endpoint in the onValidate func, but the validation call finishes a second or two before the api call. I've tried having editMode become true if there is an error, but then the cancel button doesn't work (which is expected).  Right now I am just having error text below the component. But I think it is a little confusing to the user because it does look like your input was saved (being back in display mode). And then when the user tries again, I remove the error state in my custom input component which feels a little messy.
<img width="249" alt="Screen Shot 2022-03-30 at 3 06 43 PM" src="https://user-images.githubusercontent.com/102698254/160931258-fd94cebb-f2d4-4292-89c0-1fbf41255a0e.png">
<img width="424" alt="Screen Shot 2022-03-30 at 3 20 31 PM" src="https://user-images.githubusercontent.com/102698254/160933028-b37c1704-2f62-457d-9ae0-fc06a1ca6a59.png">

**Additional context**
It would be fantastic, if the error display could look something like this...
<img width="560" alt="Screen Shot 2022-03-30 at 2 57 46 PM" src="https://user-images.githubusercontent.com/102698254/160929755-b4fa11d7-bf49-498f-8051-aa4dc77c2b06.png">

Please let me know if I can answer any questions. This is a fantastic and flexible library. Thanks for building!

**Comment by giorgosart** [comment]
Hi @lauraz33 can you please provide me with a codepen or an example showcasing the issue you are having?
