### ISSUE TITLE
Edit multiple fields as a group and save with single button

### ISSUE THREAD

**Issue by MichiyoYo** [giorgosart/react-easy-edit#143]
I am trying to add an edit mode functionality to a component that is displaying multiple fields. 
The idea is that the user can click on the component and enter edit mode so that all the fields become editable. 
Rather than having a 'Save' button per field, I'm looking to have single 'Save' button to submit the whole field group.

**Comment by giorgosart** [comment]
Do you have a codepen you can share with me?
