### ISSUE TITLE
Cannot install - ERESOLVE unable to resolve dependency tree

### ISSUE THREAD

**Issue by bouia** [giorgosart/react-easy-edit#149]
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: frontend@0.1.0
npm ERR! Found: react@18.2.0
npm ERR! node_modules/react
npm ERR! react@"^18.2.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^17.0.2" from react-easy-edit@1.15.0
npm ERR! node_modules/react-easy-edit
npm ERR!   react-easy-edit@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

**Comment by giorgosart** [comment]
@bouia please use the latest release https://www.npmjs.com/package/react-easy-edit
