### ISSUE TITLE
this library is not working with react-18  update its peer dependency

### ISSUE THREAD

**Issue by RahulPanwar05** [giorgosart/react-easy-edit#151]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by giorgosart** [comment]
Hi @RahulPanwar05 thanks for letting me know, i'll try and get a build out as soon as i can which will include react 18 as a peer dependency.

**Comment by giorgosart** [comment]
@RahulPanwar05 please use latest release https://www.npmjs.com/package/react-easy-edit
