### ISSUE TITLE
Dark Mode

### ISSUE THREAD

**Issue by guntarakesh** [giorgosart/react-easy-edit#153]
**Is your feature request related to a problem? Please describe.**
When I am using the website i wanted to enable a dark mode but its not include in the website. So if there is a Toggle button from light mode to Dark mode and ViceVersa it will helpful for user . 

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
I want to work on this issue under Hacktoberfest.

**Comment by GD0910** [comment]
can i work on this feature ? 
I am new to open source and its my first time participating in hacktoberfest

**Comment by giorgosart** [comment]
@GD0910 this ticket was created by someone else, if you have an idea then please log a ticket otherwise you can pick up either #161 or #162. Feel free to assign either or both of those tickets to yourself.

**Comment by giorgosart** [comment]
@guntarakesh done. closing ticket
