### ISSUE TITLE
Top Scroll Button

### ISSUE THREAD

**Issue by uddiptojana10** [giorgosart/react-easy-edit#160]
Adding a top scroll button for long pages would help improve user experience

For example, in the props page and in the styling page.
I would like to contribute, please assign me this under hacktoberfest label

**Comment by giorgosart** [comment]
Hello @uddiptojana10 thank you for taking an interest in my library. Can you please explain to me what the use case for this is? 

Let's take as an example the gif below that contains 3 EasyEdit components. Why would you need a scroll to top button?

![image](https://github.com/giorgosart/react-easy-edit/assets/1062121/46d692d9-d424-4e36-b70a-0d6cacabcd43)

**Comment by uddiptojana10** [comment]
my apologies i referred to this [project](https://giorgosart.gitbook.io/react-easy-edit/)

**Comment by giorgosart** [comment]
Those are my docs, im using git book so don't know if it has that feature.

**Comment by giorgosart** [comment]
@uddiptojana10 closing this ticket down, please let me know if you feel that I should reopen.
