### ISSUE TITLE
Improve unit test coverage: cover `onKeyDown` function

### ISSUE THREAD

**Issue by giorgosart** [giorgosart/react-easy-edit#161]
![image](https://github.com/giorgosart/react-easy-edit/assets/1062121/5c267cec-788a-47df-9827-8c79a3bcd614)

To run test with coverage, run `yarn run coverage` and locate the coverage report under `project root folder/coverage/lcov-report/index.html

**Comment by mnosov622** [comment]
Hi @giorgosart ,

I would love to work on it.

**Comment by giorgosart** [comment]
> @mnosov622 I'll assign this to you. Just an FYI,   this method was covered previously using Jest and Enzyme but ever since I ve updated to React 18 it stopped working. You will need to use react testing library.
