### ISSUE TITLE
Improve unit test coverage: cover `onCheckboxChange`  function

### ISSUE THREAD

**Issue by giorgosart** [giorgosart/react-easy-edit#163]
![image](https://github.com/giorgosart/react-easy-edit/assets/1062121/ac50f20e-32bf-4448-9881-d6acd413e37e)

To run test with coverage, run yarn run coverage and locate the coverage report under `project root folder/coverage/lcov-report/index.html

**Comment by TandinDev** [comment]
Can I take over this ticket?

**Comment by giorgosart** [comment]
@TandinDev I'll assign this to you. Just an FYI, this method was covered previously using Jest and Enzyme but ever since I ve updated to React 18 it stopped working. You will need to use react testing library

**Comment by TandinDev** [comment]
@giorgosart I couldn't make it work. I tried but I couldn't figure out the issue.

**Comment by giorgosart** [comment]
@TandinDev did you try writting the test using React testing library rather than jest?
