### ISSUE TITLE
Issue in merging issue #170 at automatic merging at CI test case and Scan

### ISSUE THREAD

**Issue by alpharosto** [giorgosart/react-easy-edit#172]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by giorgosart** [comment]
What's the issue @alpharosto?

**Comment by alpharosto** [comment]
Issue in merging issue #170 at automatic merging at CI test case and Scan

**Comment by giorgosart** [comment]
There is no issue with 170, can you be more specific?
