### ISSUE TITLE
Breaking after updating to 1.17.1

### ISSUE THREAD

**Issue by mahesh-trapasiya** [giorgosart/react-easy-edit#181]
**Describe the bug**
After today's update, my project is unable to resolve the package. seems like something is wrong with the build. 
Build folder is missing in the updated version

Previous Working  Version: ^1.17.0
Current Version: ^1.17.1

**To Reproduce**
1. Update the package to the latest version.

**ERROR**
ERROR in ./src/components/EditComponent.js 5:0-39
Module not found: Error: Can't resolve 'react-easy-edit' in 'D:\Project

**Comment by mjp0** [comment]
Yeah, just came to say the same thing.

**Comment by giorgosart** [comment]
@mjp0 @martoncsukas @mahesh-trapasiya issue fixed, not sure what happened there as it seems that the prepublish step that builds the lib did not happen. Try using 1.17.2 and reopen this ticket if the issue is not resolved. Thanks!
