### ISSUE TITLE
Fix SonarCloud code smells for `EasyInput.jsx`

### ISSUE THREAD

**Issue by giorgosart** [giorgosart/react-easy-edit#182]
Code smells can be found here: https://sonarcloud.io/project/issues?directories=src%2Flib&fileUuids=AYsB72ZUWgZgXcKLGRLY&resolved=false&id=giorgosart_react-easy-edit

**Comment by kareemmahlees** [comment]
Hi @giorgosart , you can assign this to me and I will work on it 🙂

**Comment by giorgosart** [comment]
@kareemmahlees this is now yours
