### ISSUE TITLE
Fix SonarCloud code smells for `EasyRadio.jsx`

### ISSUE THREAD

**Issue by giorgosart** [giorgosart/react-easy-edit#183]
Code smells can be found here: https://sonarcloud.io/project/issues?directories=src%2Flib&fileUuids=AYsB72ZUWgZgXcKLGRLU&resolved=false&id=giorgosart_react-easy-edit

**Comment by hecker8055** [comment]
Hey @giorgosart assign this to me , i wanna fix this

**Comment by giorgosart** [comment]
@hecker8055 the ticket is yours
