### ISSUE TITLE
Fix SonarCloud code smells for `EasyEdit.jsx`

### ISSUE THREAD

**Issue by giorgosart** [giorgosart/react-easy-edit#184]
Code smells can be found here: https://sonarcloud.io/project/issues?directories=src%2Flib&fileUuids=AYsB72ZUWgZgXcKLGRLO&resolved=false&id=giorgosart_react-easy-edit

**Comment by NohaFahmi** [comment]
Hi @giorgosart, I would like to work on this, please.
