### ISSUE TITLE
Fix SonarCloud code smells for `EasyDatalist.jsx`

### ISSUE THREAD

**Issue by giorgosart** [giorgosart/react-easy-edit#185]
Code smells can be found here: https://sonarcloud.io/project/issues?directories=src%2Flib&fileUuids=AYsB72ZUWgZgXcKLGRLc&resolved=false&id=giorgosart_react-easy-edit

**Comment by kareemmahlees** [comment]
@giorgosart Hi, could you assign to me?

**Comment by giorgosart** [comment]
@kareemmahlees ticket is yours
