### ISSUE TITLE
Fix SonarCloud code smells for `EasyCustom.jsx`

### ISSUE THREAD

**Issue by giorgosart** [giorgosart/react-easy-edit#186]
Code smells can be found here: https://sonarcloud.io/project/issues?directories=src%2Flib&fileUuids=AYsB72ZUWgZgXcKLGRLS&resolved=false&id=giorgosart_react-easy-edit

**Comment by AksBad007** [comment]
Hi, if this issue is still open, I'd like to be assigned.

**Comment by giorgosart** [comment]
@AksBad007 i ve assigned the ticket to you
