### ISSUE TITLE
Enhancement - Add Prettier to Improve Code Readability

### ISSUE THREAD

**Issue by rishirajm007** [giorgosart/react-easy-edit#187]
Issue Description:

I'm reaching out as an interested contributor to request to add Prettier to the project in order to improve code readability. Adding Prettier is a valuable enhancement that will ensure consistent code formatting across the codebase, making the development process more efficient and code maintenance easier.

@giorgosart 
I kindly request that you assign this issue to me under Hacktoberfest, as I am eager to work on integrating Prettier into the project and contributing to the enhancement.

**Comment by giorgosart** [comment]
@rishirajm007 happy for you to work on this
