### ISSUE TITLE
Default value. Is it posible to add a default value ?

### ISSUE THREAD

**Issue by joingenor** [giorgosart/react-easy-edit#25]
I am using a type date field. 
If the value is null i want the field to default to todays date.
I tried setting the defaultValue attribute to attributes, but then I get a nasty warning in the console:
> Warning: v contains an input of type date with both value and defaultValue props. Input elements must be either controlled or uncontrolled (specify either the value prop, or the defaultValue

Here is my settings:
```
<EasyEdit
 	type="date"
 	onSave={(e) => {
 	  this.handleChairSave(e, 'lastServiceDate');
 	}}
 	onValidate={() => true}
 	value={selectedChair.lastServiceDate?selectedChair.lastServiceDate:''}
 	saveButtonLabel={getLocalizedStrings(userLang).SAVE}
 	cancelButtonLabel={getLocalizedStrings(userLang).CANCEL}
 	placeholder={getLocalizedStrings(userLang).CLICK_EDIT}
 	saveButtonStyle={'button'}
 	cancelButtonStyle={'button'}
 	attributes={{
 	  name: 'lastServiceDate',
 	  defaultValue:'2019-04-01',
 	  id: 'lastServiceDate', style: inlineEditStyle
 	}}
/>
```

**Comment by giorgosart** [comment]
Hello @joingenor i'll take a look at this and get back to you

**Comment by giorgosart** [comment]
Instead of using the default value, could you not use the `value` prop?

```
...
value={selectedChair.lastServiceDate ? selectedChair.lastServiceDate : '2019-04-01'}
...
```

**Comment by joingenor** [comment]
I do not think that is a good solution, because then the user will think that the value is set to today's date and will not set the value...

**Comment by giorgosart** [comment]
@joingenor pushed a fix for this, can you check whether `v0.4.1` fixes your issue?

**Comment by joingenor** [comment]
This worked, but I have a suggestion for a improvement.
When the field has a default value (todays date) I think that if the user wants to just use that value the user will hit Save (I know I will). But then the value sent to the onSave event will be ''. I  have made a workaround in the onSave event in my code, but it will be nice to just get the default value passed to the onSave event

**Comment by giorgosart** [comment]
Great I'm glad it fixed your issue, closing this bug ticket for now.

Can you raise another bug ticket for the request above please?
