### ISSUE TITLE
Using fontawesome icons for saveButtonLabel & cancelButtonLabel

### ISSUE THREAD

**Issue by hnhegde** [giorgosart/react-easy-edit#37]
Easy edit really made things simple for inline editing text in React components. It would be great if saveButtonLabel & cancelButtonLabels could support FontAwesome icons. I tried it this way:
` saveButtonLabel={<FontAwesomeIcon icon={faCheck}/>}
 cancelButtonLabel={<FontAwesomeIcon icon={faTimes}/>}`
While it works, I notice following warnings in browser console logs:
`Warning: Failed prop type: Invalid prop 'saveButtonLabel' of type 'object' supplied to 'o', expected 'string'.
Warning: Failed prop type: Invalid prop 'cancelButtonLabel' of type 'object' supplied to 'o', expected 'string'.`

Would appreciate inputs on how to avoid these warnings. 

Thanks,
Harsha

**Comment by giorgosart** [comment]
Hello @hnhegde,

Thank you for logging a ticket for me.

I could change the prop type of the `saveButtonLabel` and `cancelButtonLabe`l to be either a `string` or an `object`, that should prevent the warning from being thrown. Would that work for you?

Regards,
George

**Comment by hnhegde** [comment]
Hi @giorgosart ,
`object` would be better. Thanks!
Regards,
Harsha

**Comment by giorgosart** [comment]
Released as part of 1.2.1

**Comment by giorgosart** [comment]
@hnhegde forgot to mention, the labels now accept either a string or a valid React component, not an object
