### ISSUE TITLE
Improve EasyParagraph resizing

### ISSUE THREAD

**Issue by martoncsukas** [giorgosart/react-easy-edit#38]
In `EasyParagraph.jsx` `<textarea>` should be `resize: vertical;` only. User shouldn't be able to resize the textarea to make it wider than the container element that contains it.

`<textarea>` should also fill the available horizontal space. Probably the `easy-edit-component-wrapper` class would need a `width: 100%` attribute on it.

**Comment by giorgosart** [comment]
Hello @martoncsukas,

Thank you for logging a bug ticket, but this use case should not be handled by the library itself, as the primary goal of the library is to provide user the ability to inline edit HTML component (and custom React components). 

George
