### ISSUE TITLE
Passing in `class` as an attribute overwrites your other classes

### ISSUE THREAD

**Issue by liamwithers** [giorgosart/react-easy-edit#48]
**Describe the bug**
When passing in the `attributes` prop, if you pass in an attribute of `class: 'some-class'` then it will overwrite any other classes that `react-easy-edit` has decided to add to your component, leaving you only with the value provided in your attribute prop object.

**To Reproduce**
1. Pass `{ class: 'some-class' }` in to your attributes prop
2. Notice that this is now the only class included on your rendered EasyEdit component

**Expected behavior**
Any class names that are passed in as an attribute should be _appended_ to the expected classes, rather than replacing them. How should multiple class names be passed in? As a _space separated string_, or as an array? My opinion is that some logic should be added that can append an array of class names to the other class names added by `react-easy-edit`.

**Desktop (please complete the following information):**
 - OS: All
 - Browser: All
 - Version: 1.3.1

**Additional context**
Should `setCssClasses` be renamed & generalised to set classes? Not all additional classes will necessarily be for added for styling reasons. We could alternatively have two methods (general classes & css classes), but I feel that this can be rolled into a single method.

**Comment by giorgosart** [comment]
Hey @liamwithers can you please create a code sandbox that reproduces this issue?

**Comment by liamwithers** [comment]
I can't seem replicate this now 🤷‍♂. I'll re-open this if I manage to replicate.

**Comment by liamwithers** [comment]
I've managed to replicate this. Please see here: https://codesandbox.io/s/tender-smoke-yfumn

I've noticed that this also applies to the "type" `attribute`: If you pass in the `type` **prop** "text", but you also pass in an `attribute` of "type='number'", then the attribute value will override the prop value. Do you want me to open a separate issue for this @giorgosart?

**Comment by giorgosart** [comment]
Thank you @liamwithers I can now reproduce the issue
