### ISSUE TITLE
tempValue doesn't update on component update

### ISSUE THREAD

**Issue by HarleyBartles** [giorgosart/react-easy-edit#50]
**Describe the bug**
When used within a component with pagination (e.g. react-table), paginating to a different page updates the value but not the tempValue. This means the new value displays in view mode, but in edit mode it displays the value in the same position on the previous page.

**To Reproduce**
Create a react-table with an EasyEdit element on every row
Ensure that you have more rows in your data than the pagination row size
Paginate to page 2
Verify the expected value is displayed
Enter edit mode
Verify the incorrect value is displayed

**Expected behavior**
When entering edit mode, I expect that the value displayed in view mode is what I'm editing

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: Latest

**Comment by giorgosart** [comment]
Hey @HarleyBartles thank you for logging this bug.

Will it be easy for you to create a codepen reproducing this issue?

**Comment by HarleyBartles** [comment]
Sure thing. I'll knock up a codepen for you. Probably be after the weekend tho.

**Comment by giorgosart** [comment]
No prob, thanks

**Comment by HarleyBartles** [comment]
Here's a sandbox of the issue. Paginate to page two then click on any 'Page 2' item to enter edit mode and see 'Page 1' in edit mode

https://codesandbox.io/embed/react-easy-edit-pagination-issue-bskid?fontsize=14

Hope that helps

**Comment by giorgosart** [comment]
Thanks @HarleyBartles i'll take a look in a bit

**Comment by giorgosart** [comment]
Hey @HarleyBartles, i had a look at the issue above and to me it looks like an issue with the way React-table renders each row to me. I can confirm that the value is stored in the component itself and also returned back (just change your onSave prop from `() => console.log("saved")` to `(value) => console.log(value)` to see the callback value being returned back)

Also, I can see that `tempValue` does store the correct value for the component being edited, please see below. Let me know if you still believe that the problem is with this library.

![test](https://user-images.githubusercontent.com/1062121/67645309-d129f100-f91f-11e9-9ffd-6e2ab364e62f.gif)

**Comment by HarleyBartles** [comment]
See below, I've tried to show it as clearly as I can. Changing the page of the paginated table component re-renders the easy edit component with the new value, but the temp value remains whatever was on the previous page until edit mode is entered and cancelled. Seems to me the value and tempvalue shouldn't be out of sync if the component has never entered edit mode?

1 - value and tempvalue are both "I haven't changed"
2 - I navigate to page 2
3 - value is now "I changed" and tempvalue is "I haven't changed"
4 - I enter edit mode
5 - value is still "I changed" but the displayed value in the edit box is "I haven't changed"
6 - I click cancel
7 - value is still "I changed" and now tempValue is also "I changed"

![easyedit](https://user-images.githubusercontent.com/32537371/67653698-6e961c80-f942-11e9-8305-23db3ab2ade9.gif)

**Comment by giorgosart** [comment]
Ah I see, let me take another look, the component should not re-render itself

**Comment by giorgosart** [comment]
Hey @HarleyBartles, we have now fixed this issue, i'll prepare a new release tomorrow that includes this fix and let you know

**Comment by giorgosart** [comment]
@HarleyBartles this issue is now fixed as part of 1.3.2. Let me know if the issue is resolved so that I can close this issue.

**Comment by HarleyBartles** [comment]
Thanks so much! I’ll update and check it out first thing Monday when I’m back in the office.

**Comment by HarleyBartles** [comment]
Hey George. Just to confirm this is now working. Thanks so much again for your help in getting this fixed!

**Comment by giorgosart** [comment]
@HarleyBartles there is a new version out ([1.3.3](https://www.npmjs.com/package/react-easy-edit)), make sure you upgrade to this one as it includes a few fixes for checkboxes
