### ISSUE TITLE
Add prop to hide the "Save" and "Cancel" buttons

### ISSUE THREAD

**Issue by svschannak** [giorgosart/react-easy-edit#65]
You don't always want to show the buttons to save and cancel. There is already an existing behavior to cancel and save via keys.

I would suggest a prop `hideButtons` with an default value of false.

I am already working on a PR.

**Comment by giorgosart** [comment]
@svschannak I would suggest to add two new props
* `hideSaveButton`
* `hideCancelButton`

**Comment by svschannak** [comment]
@giorgosart Sounds good. I created a PR here: https://github.com/giorgosart/react-easy-edit/pull/66

**Comment by giorgosart** [comment]
Thank you @svschannak, I've added a few comments, as soon as you've actioned them, i will merge in the PR

**Comment by giorgosart** [comment]
@svschannak did you get a chance to look at my comments in #66? As soon as you action them, I will create a build and release it.

**Comment by svschannak** [comment]
@giorgosart Yes, sorry for the delay. I pushed the changes just now :).

**Comment by giorgosart** [comment]
@svschannak, please use 1.8.0, it has your PR in it
