### ISSUE TITLE
Retrieving the dropdown attribute name when saving

### ISSUE THREAD

**Issue by jonbondani** [giorgosart/react-easy-edit#71]
Hi, 
is there any way to get the attribute's name when saving?
I have  many EasyEdit components in a single page and when trying to save the value I need the attribute's name as well.
Thanks.

**Comment by jonbondani** [comment]
Done, it was as easy as:
onSave={value => {
                    this.save(value,key)
                  }}

**Comment by giorgosart** [comment]
Glad you figured it out!
