### ISSUE TITLE
Typescript Suppport

### ISSUE THREAD

**Issue by zifahm** [giorgosart/react-easy-edit#73]
Needs typescript support.

I shall do it when I get time.

**Comment by giorgosart** [comment]
Hey @zifahm can you please elaborate a bit more around this?

**Comment by giorgosart** [comment]
Hey @zifahm I will be closing this ticket down as it has been open for a while with no traction on it. Feel free to reopen when you want to provide more information or work on it. 

Thank you for logging the ticket in the first place.

**Comment by a19i23** [comment]
I think he is asking for Typescript support. I installed and I get this
![image](https://user-images.githubusercontent.com/6509090/127355173-7e10e0e7-c298-4d62-8a78-992bfc5aec0b.png)
