### ISSUE TITLE
Out side click to save the details

### ISSUE THREAD

**Issue by itsmeganesh-cse-iiit** [giorgosart/react-easy-edit#74]
**Outside Click**

Is there any way to save the details without clicking the save button or Pressing ENTER.

It is go to name a prop like **autoSave** , so that user can save the details instantly.

**Comment by itsmeganesh-cse-iiit** [comment]
Somehow I managed this by editing **EasyEdit.jsx** with Airbnb's **react-outside-click-handler** package.

**Following are the changes to EasyEdit.jsx**

`` import OutsideClickHandler from 'react-outside-click-handler'``

in return Method of EasyEdit.jsx

`` <OutsideClickHandler onOutsideClick={this.onOutsideClick}>{this.renderInput()}</OutsideClickHandler>``

We are good with outside click save. But will face below issue , need to change css part, will update the details soon.

![outsideclick](https://user-images.githubusercontent.com/52674598/74220279-29b9aa00-4cd5-11ea-9070-b35e55186aee.png)

**Comment by giorgosart** [comment]
Hello @itsmeganesh-cse-iiit can you please provide a codepen with your solution? I can then look at this.

**Comment by itsmeganesh-cse-iiit** [comment]
Sure @giorgosart  I have implemented with outside click functionality and also integrated react tags types in EasyEdit file, will share the code by EOD.

**Comment by giorgosart** [comment]
@itsmeganesh-cse-iiit I've added `onBlur` support for `EasyEdit` components, can you check if that solves your issue?

**Comment by itsmeganesh-cse-iiit** [comment]
Sure @giorgosart, still customizing that's why not updated the code pen, I have added the react-select library  tag support locally, like TYPES=tags

**Comment by dzsodzso63** [comment]
I'm thinking about a solution where the return value of onBlur could save. e.g. `onBlur={(tempVal) => true}`

**Comment by giorgosart** [comment]
@itsmeganesh-cse-iiit I will close this ticket down, feel free to reopen when you have a solution in mind.
